spring:
  application:
    name: eureka-server
---
spring:
  profiles: peer1
server:
   port: 8761
eureka:
   instance:
      hostname: peer1
   client:
      serviceUrl:
         defaultZone: http://peer2:8762/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

---
spring:
  profiles: peer2
server:
   port: 8762
eureka:
   instance:
      hostname: peer2
   client:
      serviceUrl:
         defaultZone: http://peer1:8761/eureka/
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF