eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.3.60:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: user-service
  zipkin:
    baseUrl: http://localhost:9411
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0