spring:
  application:
    name: eureka-feign-client
server:
  port: 8765

eureka:
  client:
    serviceUrl:
       defaultZone: http://172.16.3.60:8761/eureka/,http://172.16.3.60:8762/eureka/
#      defaultZone: http://172.16.3.60:8761/eureka/,http://172.16.3.60:8762/eureka/,http://172.16.3.60:8763/eureka/
#      defaultZone: http://localhost:8761/eureka/
